# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91a538dfae96e450d66208d242919411ecf414fc3e891fee36b27aaa1929ca8c9dd19fb361d47e4bc048f2771905c2f56fc22040f0e4cad2b81a4cd8a16a6d2c

test:
  secret_key_base: 8907e4a93ca643c5cceaab4dd9f2119b3a4363205a98c37b93565deb086537f9293d21b5eab827185bd0ec8aecaf69fe080667f740a9e916f75d13835f55b3f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
